/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-01-27 07:22:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.console;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>qnsport Administrator's Control Panel - powered by\r\n");
      out.write("\tqnsport</title>\r\n");
      out.write("<link href=\"/jsutils/qingniao/css/admin.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"/jsutils/common/css/theme.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"/jsutils/common/css/jquery.validate.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"/jsutils/common/css/jquery.treeview.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"/jsutils/common/css/jquery.ui.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- <script src=\"/thirdparty/ckeditor/ckeditor.js\" type=\"text/javascript\"></script> -->\r\n");
      out.write("<!-- <script src=\"/thirdparty/My97DatePicker/WdatePicker.js\" type=\"text/javascript\"></script> -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/jsutils/fckeditor/fckeditor.js\"></script>\r\n");
      out.write("<script src=\"/jsutils/common/js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/jsutils/common/js/jquery.ext.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/jsutils/common/js/jquery.form.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/jsutils/common/js/qingniao.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/jsutils/qingniao/js/admin.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:focus {\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#top {\r\n");
      out.write("\tbackground-color: #bfd2f2;\r\n");
      out.write("\theight: 69px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("\twidth: 215px;\r\n");
      out.write("\theight: 69px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topbg {\r\n");
      out.write("\tbackground: url(/jsutils/qingniao/img/admin/top-tbg.png) no-repeat;\r\n");
      out.write("\theight: 38px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-welcome {\r\n");
      out.write("\tpadding-left: 20px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tbackground: url(/jsutils/qingniao/img/admin/topbg.gif) no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-welcome a:link, .login-welcome a:visited {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#welcome {\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("\tpadding: 0 30px 0 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logout {\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("\tpadding-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav {\r\n");
      out.write("\theight: 31px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-menu {\r\n");
      out.write("\tbackground: url(/jsutils/qingniao/img/admin/bg.png) repeat-x;\r\n");
      out.write("\theight: 31px;\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tpadding-left: 20px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav .current {\r\n");
      out.write("\tbackground: url(/jsutils/qingniao/img/admin/navcurrbg.gif) no-repeat 0px\r\n");
      out.write("\t\t2px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\twidth: 72px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav .current a {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-menu li {\r\n");
      out.write("\theight: 31px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 31px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-menu li a {\r\n");
      out.write("\tcolor: #2b2b2b;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-menu li.sep {\r\n");
      out.write("\tbackground: url(/jsutils/qingniao/img/admin/step.png) no-repeat;\r\n");
      out.write("\twidth: 2px;\r\n");
      out.write("\theight: 31px;\r\n");
      out.write("\tmargin: 0px 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav .normal {\r\n");
      out.write("\twidth: 72px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bottom {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\t/*background: url(/jsutils/qingniao/img/admin/bg.png) repeat-x 0px -34px;*/\r\n");
      out.write("\tbackground-color: #bfd2f2;\r\n");
      out.write("\theight: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".undis {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dis {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tfunction HoverLi(id) {\r\n");
      out.write("\t\t\t\t$(\"li[id^='tb_']\").each(function() {\r\n");
      out.write("\t\t\t\t\t$(this).removeClass(\"current\");\r\n");
      out.write("\t\t\t\t\t$(this).addClass(\"normal\");\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#tb_\" + id).removeClass(\"normal\");\r\n");
      out.write("\t\t\t\t$(\"#tb_\" + id).addClass(\"current\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"top\">\r\n");
      out.write("\t\t<div class=\"top\">\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"215\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/jsutils/qingniao/img/admin/logo.jpg\" width=\"215\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"69\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"topbg\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-welcome\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"420\" height=\"38\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"/jsutils/qingniao/img/admin/welconlogin-icon.png\" /> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"logout.do?returnUrl=index.do\" target=\"_top\" id=\"logout\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"return confirm('您确定退出吗?');\">登录</a> &nbsp; &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp; <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"/jsutils/qingniao/img/admin/loginout-icon.png\" /> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"logout.do?returnUrl=index.do\" target=\"_top\" id=\"logout\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"return confirm('您确定退出吗?');\">退出</a> </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"background-image: url('/jsutils/qingniao/img/admin/nav-left.png')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twidth=\"14\" height=\"31\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"nav-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"current\" id=\"tb_11\" onclick=\"HoverLi(11);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"main.do\" target=\"mainFrame\">首页</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"normal\" id=\"tb_12\" onclick=\"HoverLi(12);\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"productMain.do\" target=\"mainFrame\">商品管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"normal\" id=\"tb_13\" onclick=\"HoverLi(13);\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"orderMain.do\" target=\"mainFrame\">订单管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"normal\" id=\"tb_14\" onclick=\"HoverLi(14);\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"frame/product_main.jsp\" target=\"mainFrame\">财务结算</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"normal\" id=\"tb_15\" onclick=\"HoverLi(15);\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"frame/product_main.jsp\" target=\"mainFrame\">基本资料</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"normal\" id=\"tb_16\" onclick=\"HoverLi(16);\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"frame/product_main.jsp\" target=\"mainFrame\">服务专享</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"normal\" id=\"tb_19\" onclick=\"HoverLi(19);\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"frame/product_main.jsp\" target=\"mainFrame\">用户管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"normal\" id=\"tb_20\" onclick=\"HoverLi(20);\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"frame/product_main.jsp\" target=\"mainFrame\">物流管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"top-bottom\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
