/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-02-23 10:34:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.partal.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class productDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expijsutils\" content=\"0\">    \r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>青鸟运动购物平台-商品详情页</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/jsutils/css/style.css\" />\r\n");
      out.write("<script src=\"/jsutils/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/jsutils/js/com.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".changeToRed {\r\n");
      out.write("\tborder: 2px solid #e4393c;\r\n");
      out.write("\tpadding: 2px 4px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-right: 4px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".changeToWhite {\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tpadding: 2px 4px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-right: 4px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".not-allow {\r\n");
      out.write("\tcursor: not-allowed;\r\n");
      out.write("\tcolor: #999;\r\n");
      out.write("\tborder: 1px dashed #ccc;\r\n");
      out.write("\tpadding: 2px 4px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-right: 4px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar gColorId;\r\n");
      out.write("\tvar gSize;\r\n");
      out.write("\tvar gskuId;\r\n");
      out.write("\tvar gupperLimit;\r\n");
      out.write("\t//页面你初始化\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#colors a:first\").trigger(\"click\");\r\n");
      out.write("\t\t//增加购买件数\r\n");
      out.write("\t\t$(\"#add\").click(function() {\r\n");
      out.write("\t\t\t//获取文本框里面的值\r\n");
      out.write("\t\t\tvar num = $(\"#num\").val();\r\n");
      out.write("\t\t\tif (num < gupperLimit) {\r\n");
      out.write("\t\t\t\tnum++;\r\n");
      out.write("\t\t\t\t$(\"#num\").val(num);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert(\"超出购买限制！\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t//减少购买件数\r\n");
      out.write("\t\t$(\"#sub\").click(function() {\r\n");
      out.write("\t\t\t//获取文本框里面的值\r\n");
      out.write("\t\t\tvar num = $(\"#num\").val();\r\n");
      out.write("\t\t\tif (num > 1) {\r\n");
      out.write("\t\t\t\tnum--;\r\n");
      out.write("\t\t\t\t$(\"#num\").val(num);\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t//变换颜色\r\n");
      out.write("\tfunction changeColor(obj, colorId) {\r\n");
      out.write("\t\tvar flag = true;\r\n");
      out.write("\t\tgColorId = colorId;\r\n");
      out.write("\t\t//清除之前选择的颜色\r\n");
      out.write("\t\t$(\"#colors a\").attr(\"class\", \"changeToWhite\");\r\n");
      out.write("\t\t//清除显示的尺码\r\n");
      out.write("\t\t$(\"#sizes a\").attr(\"class\", \"not-allow\");\r\n");
      out.write("\t\t//选择颜色\r\n");
      out.write("\t\t$(obj).attr(\"class\", \"changeToRed\");\r\n");
      out.write("\t\t//列出颜色所对应的尺码\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changeSize(obj, size) {\r\n");
      out.write("\t\tif($(obj).attr(\"class\") == \"changeToWhite\") {\r\n");
      out.write("\t\t\t//清空之前选择的尺码\r\n");
      out.write("\t\t\t$(\"#sizes a\").each(function() {\r\n");
      out.write("\t\t\t\tif ($(this).attr(\"class\") == \"changeToRed\") {\r\n");
      out.write("\t\t\t\t\t$(this).attr(\"class\", \"changeToWhite\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t//选择尺码\r\n");
      out.write("\t\t\tgSize = size;\r\n");
      out.write("\t\t\t$(obj).attr(\"class\", \"changeToRed\");\r\n");
      out.write("\t\t\t//确定显示价格\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//登陆\r\n");
      out.write("\tfunction login() {\r\n");
      out.write("\t\twindow.location.href = \"/login.html?url=\"+encodeURIComponent(window.location.href);\r\n");
      out.write("\t}\r\n");
      out.write("\t//购买按钮\r\n");
      out.write("\tfunction buy() {\r\n");
      out.write("\t\twindow.location.href = \"/buy/shopping.html?skuId=\"+gskuId+\"&amount=\"+$(\"#num\").val()+\"&url=\"+encodeURIComponent(window.location.href);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"bar\"><div class=\"bar_w\">\r\n");
      out.write("\t\r\n");
      out.write("\t<p class=\"l\">\r\n");
      out.write("\t\t<span class=\"l\">\r\n");
      out.write("\t\t\t收藏本网站！北京<a href=\"#\" title=\"更换\">[更换]</a>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<ul class=\"r uls\">\r\n");
      out.write("\t\t<li class=\"dev\">\r\n");
      out.write("\t\t\t您好,欢迎来到青鸟运动购物平台！\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<li class=\"dev\"><a href=\"javascript:void(0)\" onclick=\"logout()\" title=\"退出\">[退出]</a></li>\r\n");
      out.write("\t\t<li class=\"dev\"><a href=\"javascript:void(0)\" onclick=\"myOrder()\" title=\"我的订单\">我的订单</a></li>\r\n");
      out.write("\t\t<li class=\"dev\"><a href=\"#\" title=\"在线客服\">在线客服</a></li>\r\n");
      out.write("\t\t<li class=\"dev after\"><a href=\"#\" title=\"English\">English</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div></div>\r\n");
      out.write("<div class=\"w loc\">\r\n");
      out.write("\t<div class=\"h-title\">\r\n");
      out.write("\t\t<div class=\"h-logo\"><a href=\"http://localhost:8080\"><img src=\"/jsutils/img/pic/logo-3.png\" /></a></div>\r\n");
      out.write("\t    <div class=\"h-search\">\r\n");
      out.write("\t      \t<input type=\"text\" />\r\n");
      out.write("\t        <div class=\"h-se-btn\"><a href=\"#\">搜索</a></div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<dl id=\"cart\" class=\"cart r\">\r\n");
      out.write("\t\t<dt><a href=\"#\" title=\"结算\">结算</a>购物车:<b id=\"\">123</b>件</dt>\r\n");
      out.write("\t\t<dd class=\"hidden\">\r\n");
      out.write("\t\t\t<p class=\"alg_c hidden\">购物车中还没有商品，赶紧选购吧！</p>\r\n");
      out.write("\t\t\t<h3 title=\"最新加入的商品\">最新加入的商品</h3>\r\n");
      out.write("\t\t\t<ul class=\"uls\">\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/jsutils/img/pic/p50x50.jpg\" alt=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\" /></a>\r\n");
      out.write("\t\t\t\t\t<p class=\"dt\"><a href=\"#\" title=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\">依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元</a></p>\r\n");
      out.write("\t\t\t\t\t<p class=\"dd\">\r\n");
      out.write("\t\t\t\t\t\t<b><var>¥128</var><span>x1</span></b>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0);\" title=\"删除\" class=\"del\">删除</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/jsutils/img/pic/p50x50.jpg\" alt=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\" /></a>\r\n");
      out.write("\t\t\t\t\t<p class=\"dt\"><a href=\"#\" title=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\">依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元</a></p>\r\n");
      out.write("\t\t\t\t\t<p class=\"dd\">\r\n");
      out.write("\t\t\t\t\t\t<b><var>¥128</var><span>x1</span></b>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0);\" title=\"删除\" class=\"del\">删除</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/jsutils/img/pic/p50x50.jpg\" alt=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\" /></a>\r\n");
      out.write("\t\t\t\t\t<p class=\"dt\"><a href=\"#\" title=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\">依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元</a></p>\r\n");
      out.write("\t\t\t\t\t<p class=\"dd\">\r\n");
      out.write("\t\t\t\t\t\t<b><var>¥128</var><span>x1</span></b>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0);\" title=\"删除\" class=\"del\">删除</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/jsutils/img/pic/p50x50.jpg\" alt=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\" /></a>\r\n");
      out.write("\t\t\t\t\t<p class=\"dt\"><a href=\"#\" title=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\">依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元</a></p>\r\n");
      out.write("\t\t\t\t\t<p class=\"dd\">\r\n");
      out.write("\t\t\t\t\t\t<b><var>¥128</var><span>x1</span></b>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0);\" title=\"删除\" class=\"del\">删除</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/jsutils/img/pic/p50x50.jpg\" alt=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\" /></a>\r\n");
      out.write("\t\t\t\t\t<p class=\"dt\"><a href=\"#\" title=\"依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元\">依琦莲2014瑜伽服套装新 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色 M全场支持货到付款 全网最低价 千人超高好评瑜伽服赶紧抢！全五分好评截图联系客服还返现五元</a></p>\r\n");
      out.write("\t\t\t\t\t<p class=\"dd\">\r\n");
      out.write("\t\t\t\t\t\t<b><var>¥128</var><span>x1</span></b>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0);\" title=\"删除\" class=\"del\">删除</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p>共<b>5</b>件商品&nbsp;&nbsp;&nbsp;&nbsp;共计<b class=\"f20\">¥640.00</b></p>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"去购物车结算\" class=\"inb btn120x30c\">去购物车结算</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</dd>\r\n");
      out.write("\t</dl>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"w ofc mt\">\r\n");
      out.write("\t<div class=\"l\">\r\n");
      out.write("\t\t<div class=\"showPro\">\r\n");
      out.write("\t\t\t<div class=\"big\"><a id=\"showImg\" class=\"cloud-zoom\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.img.imgUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" rel=\"adjustX:10,adjustY:-1\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.img.imgUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></a></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"r\" style=\"width: 640px\">\r\n");
      out.write("\t\t<ul class=\"uls form\">\r\n");
      out.write("\t\t\t<li><h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h2></li>\r\n");
      out.write("\t\t\t<li><label>价 格：</label><span class=\"word\"><b class=\"f14 red mr\" id=\"pprice\" >￥</b>(市场价:<del id=\"pmarketprice\" >￥</del>)</span></li>\r\n");
      out.write("\t\t\t<li><label>商品评价：</label><span class=\"word\"><span class=\"val_no val3d4\" title=\"4分\">4分</span><var class=\"blue\">(已有888人评价)</var></span></li>\r\n");
      out.write("\t\t\t<li><label>运　　费：</label><span class=\"word\" id=\"pdeliveFee\" ></span></li>\r\n");
      out.write("\t\t\t<li><label>库　　存：</label><span class=\"word\" id=\"pstock\"></span><span class=\"word\" >件</span></li>\r\n");
      out.write("\t\t\t<li><label>选择颜色：</label>\r\n");
      out.write("\t\t\t\t<div id=\"colors\" class=\"pre spec\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li id=\"sizes\"><label>尺　　码：</label>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"not-allow\" onclick=\"changeSize(this,'S');\" id=\"S\">S</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"not-allow\" onclick=\"changeSize(this,'M');\" id=\"M\">M</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"not-allow\" onclick=\"changeSize(this,'L');\" id=\"L\">L</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"not-allow\" onclick=\"changeSize(this,'XL');\" id=\"XL\">XL</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"not-allow\" onclick=\"changeSize(this,'XXL');\" id=\"XXL\">XXL</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li><label>我 要 买：</label>\r\n");
      out.write("\t\t\t\t<a id=\"sub\" class=\"inb arr\" style=\"border: 1px solid #919191;width: 10px;height: 10px;line-height: 10px;text-align: center;\" title=\"减\" href=\"javascript:void(0);\" >-</a>\r\n");
      out.write("\t\t\t\t<input id=\"num\" type=\"text\" value=\"1\" name=\"\" size=\"1\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t<a id=\"add\" class=\"inb arr\" style=\"border: 1px solid #919191;width: 10px;height: 10px;line-height: 10px;text-align: center;\" title=\"加\" href=\"javascript:void(0);\">+</a></li>\r\n");
      out.write("\t\t\t<li class=\"submit\"><input type=\"button\" value=\"\" class=\"hand btn138x40\" onclick=\"buy()\"/><input type=\"button\" value=\"\" class=\"hand btn138x40b\" onclick=\"addCart()\"/></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"w ofc mt\">\r\n");
      out.write("<div class=\"l wl\">\r\n");
      out.write("\t<h2 class=\"h2 h2_l mt\"><em title=\"销量排行榜\">销量排行榜</em><cite></cite></h2>\r\n");
      out.write("\t<div class=\"box bg_white\">\r\n");
      out.write("\t\t<ul class=\"uls x_50x50\">\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<var class=\"sfont\">1</var>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<var class=\"sfont\">2</var>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp1.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<var class=\"sfont\">3</var>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp2.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp3.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp4.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp5.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp6.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<h2 class=\"h2 h2_l mt\"><em title=\"我的浏览记录\">我的浏览记录</em><cite></cite></h2>\r\n");
      out.write("\t<div class=\"box bg_white\">\r\n");
      out.write("\t\t<ul class=\"uls x_50x50\">\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp1.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp2.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp3.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp4.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"富一代\" target=\"_blank\" class=\"pic\"><img src=\"/jsutils/img/pic/ppp5.jpg\" alt=\"依琦莲2014瑜伽服套装新\" /></a>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<!-- dt 8个文字+... -->\r\n");
      out.write("\t\t\t\t\t<dt><a href=\"#\" title=\"依琦莲2014瑜伽服套装新\" target=\"_blank\">依琦莲2014瑜伽服套装新</a></dt>\r\n");
      out.write("\t\t\t\t\t<dd class=\"orange\">￥120 ~ ￥150</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<h2 class=\"h2 h2_l mt\"><em title=\"商家精选\">商家精选</em><cite></cite></h2>\r\n");
      out.write("\t<img src=\"/jsutils/img/pic/ad200x75.jpg\" alt=\"\" />\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"r wr\">\r\n");
      out.write("\t\t<h2 class=\"h2 h2_ch mt\"><em>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0);\" title=\"商品介绍\" rel=\"#detailTab1\" class=\"here\">商品介绍</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0);\" title=\"规格参数\" rel=\"#detailTab2\">规格参数</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0);\" title=\"包装清单\" rel=\"#detailTab3\">包装清单</a></em><cite></cite></h2>\r\n");
      out.write("\t\t<div class=\"box bg_white ofc\">\r\n");
      out.write("\t\t\t<div id=\"detailTab1\" class=\"detail\">\r\n");
      out.write("\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.description }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"detailTab2\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t<strong>服务承诺：</strong><br>\r\n");
      out.write("\t京东向您保证所售商品均为正品行货，京东自营商品开具机打发票或电子发票。凭质保证书及京东发票，可享受全国联保服务（奢侈品、钟表除外；奢侈品、钟表由京东联系保修，享受法定三包售后服务），与您亲临商场选购的商品享受相同的质量保证。京东还为您提供具有竞争力的商品价格和<a target=\"_blank\" href=\"http://www.jd.com/help/kdexpjsutilss.aspx\">运费政策</a>，请您放心购买！\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t注：因厂家会在没有任何提前通知的情况下更改产品包装、产地或者一些附件，本司不能确保客户收到的货物与商城图片、产地、附件说明完全一致。只能确保为原厂正货！并且保证与当时市场上同样主流新品一致。若本商城没有及时更新，请大家谅解！ <br/>\r\n");
      out.write("\t\t<strong>权利声明：</strong><br>京东上的所有商品信息、客户评价、商品咨询、网友讨论等内容，是京东重要的经营资源，未经许可，禁止非法转载使用。\r\n");
      out.write("\t<p><b>注：</b>本站商品信息均来自于合作方，其真实性、准确性和合法性由信息拥有者（合作方）负责。本站不提供任何保证，并不承担任何法律责任。</p>\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"detailTab3\" class=\"detail\" style=\"display:none\">\r\n");
      out.write("\r\n");
      out.write("\t<pre class=\"f14\">\r\n");
      out.write("\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.packageList }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" \r\n");
      out.write("\t</pre>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"mode\">\r\n");
      out.write("\t<div class=\"tl\"></div><div class=\"tr\"></div>\r\n");
      out.write("\t<ul class=\"uls\">\r\n");
      out.write("\t\t<li class=\"first\">\r\n");
      out.write("\t\t\t<span class=\"guide\"></span>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t<dt title=\"购物指南\">购物指南</dt>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" title=\"购物流程\">购物流程</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" title=\"购物流程\">购物流程</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" target=\"_blank\" title=\"联系客服\">联系客服</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" target=\"_blank\" title=\"联系客服\">联系客服</a></dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<span class=\"way\"></span>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t<dt title=\"支付方式\">支付方式</dt>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" title=\"货到付款\">货到付款</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" title=\"在线支付\">在线支付</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" title=\"分期付款\">分期付款</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" title=\"分期付款\">分期付款</a></dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<span class=\"help\"></span>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t<dt title=\"配送方式\">配送方式</dt>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" title=\"上门自提\">上门自提</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" title=\"上门自提\">上门自提</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" title=\"上门自提\">上门自提</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" title=\"上门自提\">上门自提</a></dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<span class=\"service\"></span>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t<dt title=\"售后服务\">售后服务</dt>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" target=\"_blank\" title=\"售后策略\">售后策略</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" target=\"_blank\" title=\"售后策略\">售后策略</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" target=\"_blank\" title=\"售后策略\">售后策略</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" target=\"_blank\" title=\"售后策略\">售后策略</a></dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<span class=\"problem\"></span>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t<dt title=\"特色服务\">特色服务</dt>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" target=\"_blank\" title=\"夺宝岛\">夺宝岛</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" target=\"_blank\" title=\"夺宝岛\">夺宝岛</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" target=\"_blank\" title=\"夺宝岛\">夺宝岛</a></dd>\r\n");
      out.write("\t\t\t<dd><a href=\"#\" target=\"_blank\" title=\"夺宝岛\">夺宝岛</a></dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/partal/product/productDetail.jsp(84,2) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${skuList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /WEB-INF/partal/product/productDetail.jsp(84,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("sku");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\tif (colorId == '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.colorId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("') {\r\n");
            out.write("\t\t\t\t//默认选择第一个尺码并显示信息\r\n");
            out.write("\t\t\t\tif (flag) {\r\n");
            out.write("\t\t\t\t\t$(\"#");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.size}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\").attr(\"class\", \"changeToRed\");\r\n");
            out.write("\t\t\t\t\t//显示价格\r\n");
            out.write("\t\t\t\t\t$(\"#pprice\").html(\"￥");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\");\r\n");
            out.write("\t\t\t\t\t//显示市场价格\r\n");
            out.write("\t\t\t\t\t$(\"#pmarketprice\").html(\"￥");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.marketPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\");\r\n");
            out.write("\t\t\t\t\t//显示运费\r\n");
            out.write("\t\t\t\t\t$(\"#pdeliveFee\").html(\"￥");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.deliveFee}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\");\r\n");
            out.write("\t\t\t\t\t//显示库存\r\n");
            out.write("\t\t\t\t\t$(\"#pstock\").html(\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\");\r\n");
            out.write("\t\t\t\t\tgskuId = ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(";\r\n");
            out.write("\t\t\t\t\tgupperLimit = ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.upperLimit}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(";\r\n");
            out.write("\t\t\t\t\tflag = false;\r\n");
            out.write("\t\t\t\t} else {\r\n");
            out.write("\t\t\t\t\t$(\"#");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.size}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\").attr(\"class\", \"changeToWhite\");\r\n");
            out.write("\t\t\t\t}\r\n");
            out.write("\t\t\t}\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/partal/product/productDetail.jsp(121,3) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${skuList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /WEB-INF/partal/product/productDetail.jsp(121,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("sku");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\tif (gColorId == '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.colorId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("' && size == '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.size}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("') {\r\n");
            out.write("\t\t\t\t\t//显示价格\r\n");
            out.write("\t\t\t\t\t$(\"#pprice\").html(\"￥");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\");\r\n");
            out.write("\t\t\t\t\t//显示市场价格\r\n");
            out.write("\t\t\t\t\t$(\"#pmarketprice\").html(\"￥");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.marketPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\");\r\n");
            out.write("\t\t\t\t\t//显示运费\r\n");
            out.write("\t\t\t\t\t$(\"#pdeliveFee\").html(\"￥");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.deliveFee}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\");\r\n");
            out.write("\t\t\t\t\t//显示库存\r\n");
            out.write("\t\t\t\t\t$(\"#pstock\").html(\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\");\r\n");
            out.write("\t\t\t\t\tgskuId = ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(";\r\n");
            out.write("\t\t\t\t\tgupperLimit = ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sku.upperLimit}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(";\r\n");
            out.write("\t\t\t\t}\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/partal/product/productDetail.jsp(159,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!isLogin }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<li class=\"dev\"><a href=\"javascript:void(0)\" onclick=\"login()\"  title=\"登陆\">[登陆]</a></li>\r\n");
          out.write("\t\t\t<li class=\"dev\"><a href=\"javascript:void(0)\" onclick=\"register()\" title=\"免费注册\">[免费注册]</a></li>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/partal/product/productDetail.jsp(252,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colorList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /WEB-INF/partal/product/productDetail.jsp(252,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("color");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<a onclick=\"changeColor(this,'");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("')\" href=\"javascript:void(0)\" title=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" class=\"changeToWhite\"><img width=\"25\" height=\"25\" data-img=\"1\" src=\"/jsutils/img/pic/ppp00.jpg\" alt=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(" \"><i>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</i></a>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
